name: bazario
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.5
  firebase_messaging: ^14.7.17     # ✅ Add this line
  image_picker: ^1.1.0
  provider: ^6.1.2
  razorpay_flutter: ^1.3.5

  # ✅ Added for PDF Generation & Printing
  pdf: ^3.10.8
  printing: ^5.12.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
